from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT

def generate_legal_pdf(text_content, filename):
    """
    Generates a professional legal PDF from text input.
    """
    doc = SimpleDocTemplate(filename, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', alignment=TA_JUSTIFY))
    styles.add(ParagraphStyle(name='Disclaimer', fontSize=8, textColor='grey', alignment=TA_CENTER))

    Story = []

    # 1. Header
    title_style = styles["Heading1"]
    title_style.alignment = TA_LEFT
    Story.append(Paragraph("Juris AI Legal Defender - Draft Notice", title_style))
    Story.append(Spacer(1, 12))

    # 2. Main Content (Handling basic newlines)
    # Split by double newlines to find paragraphs
    paragraphs = text_content.split('\n\n')
    normal_style = styles["Normal"]
    normal_style.fontSize = 11
    normal_style.leading = 14

    for p_text in paragraphs:
        # Simple cleanup
        clean_text = p_text.replace('\n', ' ').strip()
        if clean_text:
            Story.append(Paragraph(clean_text, normal_style))
            Story.append(Spacer(1, 12))

    # 3. Signature Line
    Story.append(Spacer(1, 48))
    Story.append(Paragraph("__________________________", normal_style))
    Story.append(Paragraph("Tenant Signature", normal_style))
    
    # 4. Disclaimer Footer
    Story.append(Spacer(1, 48))
    disclaimer_text = "DISCLAIMER: This document was generated by an AI research tool. It is not legal advice. Please review with a qualified legal professional before sending."
    # Story.append(Paragraph(disclaimer_text, styles["Disclaimer"])) # Fix style access
    
    doc.build(Story)
    return filename

if __name__ == "__main__":
    # Test
    sample_text = "To Landlord,\n\nI am writing to object to the rent increase."
    generate_legal_pdf(sample_text, "test_notice.pdf")
    print("PDF Generated.")
